### ISSUE TITLE
Box-sizing global rule

### ISSUE THREAD

**Issue by katevoss** [catalpainternational/canoe#494]
Look into adding `box-sixing: border-box` to all elements:
```css
html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
```
From this blog: https://www.paulirish.com/2012/box-sizing-border-box-ftw/
There's even an (unofficial) appreciation day! https://css-tricks.com/international-box-sizing-awareness-day/

More links:

- https://css-tricks.com/box-sizing/
- https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
